// @formatter:off
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.github.syafiqq.entra.lvq.view;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;

/**
 *
 * @author Entra
 */
public class FormUtama extends javax.swing.JFrame {

    private JInternalFrame dataset; /**
     * Creates new form FormUtama
     */
    public FormUtama() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenu = new javax.swing.JMenuItem();
        lvqMenu = new javax.swing.JMenu();
        datasetMenu = new javax.swing.JMenuItem();
        trainingMenu = new javax.swing.JMenuItem();
        testingMenu = new javax.swing.JMenuItem();
        viewMenu = new javax.swing.JMenu();
        jaraktrainingMenu = new javax.swing.JMenuItem();
        bobottrainingMenu = new javax.swing.JMenuItem();
        jaraktestingMenu = new javax.swing.JMenuItem();
        testMenu = new javax.swing.JMenu();
        testalphaMenu = new javax.swing.JMenuItem();
        testdecalphaMenu = new javax.swing.JMenuItem();
        testminalphaMenu = new javax.swing.JMenuItem();
        testmaxepohMenu = new javax.swing.JMenuItem();
        testdataMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        fileMenu.setText("File");

        exitMenu.setText("Exit");
        exitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenu);

        jMenuBar1.add(fileMenu);

        lvqMenu.setText("Menu LVQ");

        datasetMenu.setText("Dataset Penyakit Mata");
        datasetMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datasetMenuActionPerformed(evt);
            }
        });
        lvqMenu.add(datasetMenu);

        trainingMenu.setText("Proses Pelatihan LVQ");
        trainingMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainingMenuActionPerformed(evt);
            }
        });
        lvqMenu.add(trainingMenu);

        testingMenu.setText("Proses Pengujian LVQ");
        testingMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testingMenuActionPerformed(evt);
            }
        });
        lvqMenu.add(testingMenu);

        jMenuBar1.add(lvqMenu);

        viewMenu.setText("View");

        jaraktrainingMenu.setText("Proses Perhitungan Jarak Data Latih (Training)");
        jaraktrainingMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaraktrainingMenuActionPerformed(evt);
            }
        });
        viewMenu.add(jaraktrainingMenu);

        bobottrainingMenu.setText("Proses Perhitungan Bobot Data Latih (Training)");
        bobottrainingMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bobottrainingMenuActionPerformed(evt);
            }
        });
        viewMenu.add(bobottrainingMenu);

        jaraktestingMenu.setText("Proses Perhitungan Jarak Data Uji (Testing)");
        jaraktestingMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaraktestingMenuActionPerformed(evt);
            }
        });
        viewMenu.add(jaraktestingMenu);

        jMenuBar1.add(viewMenu);

        testMenu.setText("Test Parameters");

        testalphaMenu.setText("Pengujian Learning Rate (α)");
        testalphaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testalphaMenuActionPerformed(evt);
            }
        });
        testMenu.add(testalphaMenu);

        testdecalphaMenu.setText("Pengujian Pengurangan Learning Rate (Dec α)");
        testdecalphaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testdecalphaMenuActionPerformed(evt);
            }
        });
        testMenu.add(testdecalphaMenu);

        testminalphaMenu.setText("Pengujian Minimal Learning Rate (Min α)");
        testminalphaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testminalphaMenuActionPerformed(evt);
            }
        });
        testMenu.add(testminalphaMenu);

        testmaxepohMenu.setText("Pengujian Iterasi Maksimum (MaxEpoh)");
        testmaxepohMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testmaxepohMenuActionPerformed(evt);
            }
        });
        testMenu.add(testmaxepohMenu);

        testdataMenu.setText("Perbandingan Data Latih : Data Uji");
        testdataMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testdataMenuActionPerformed(evt);
            }
        });
        testMenu.add(testdataMenu);

        jMenuBar1.add(testMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMenuActionPerformed

    private void datasetMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datasetMenuActionPerformed
        // TODO add your handling code here:
        try {
            if(this.dataset == null)
            {
                this.dataset = new DatasetPenyakitMataFrame();
                this.jDesktopPane1.add(dataset);
                this.dataset.setMaximum(true);
            }
            this.dataset.show();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FormUtama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_datasetMenuActionPerformed

    private void trainingMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainingMenuActionPerformed
        // TODO add your handling code here:
        try {
            ProsesPelatihanLVQFrame dataset = new ProsesPelatihanLVQFrame();
            jDesktopPane1.add(dataset);
            dataset.setMaximum(true);
            dataset.show();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FormUtama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_trainingMenuActionPerformed

    private void testingMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testingMenuActionPerformed
        // TODO add your handling code here:
        try {
            ProsesPengujianLVQFrame dataset = new ProsesPengujianLVQFrame();
            jDesktopPane1.add(dataset);
            dataset.setMaximum(true);
            dataset.show();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FormUtama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_testingMenuActionPerformed

    private void jaraktrainingMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaraktrainingMenuActionPerformed
        // TODO add your handling code here:
        try {
            JarakTrainingFrame dataset = new JarakTrainingFrame();
            jDesktopPane1.add(dataset);
            dataset.setMaximum(true);
            dataset.show();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FormUtama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jaraktrainingMenuActionPerformed

    private void bobottrainingMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bobottrainingMenuActionPerformed
        // TODO add your handling code here:
        try {
            BobotTrainingFrame dataset = new BobotTrainingFrame();
            jDesktopPane1.add(dataset);
            dataset.setMaximum(true);
            dataset.show();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FormUtama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bobottrainingMenuActionPerformed

    private void jaraktestingMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaraktestingMenuActionPerformed
        // TODO add your handling code here:
        try {
            JarakTestingFrame dataset = new JarakTestingFrame();
            jDesktopPane1.add(dataset);
            dataset.setMaximum(true);
            dataset.show();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FormUtama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jaraktestingMenuActionPerformed

    private void testalphaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testalphaMenuActionPerformed
        // TODO add your handling code here:
        try {
            PengujianAlphaFrame dataset = new PengujianAlphaFrame();
            jDesktopPane1.add(dataset);
            dataset.setMaximum(true);
            dataset.show();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FormUtama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_testalphaMenuActionPerformed

    private void testdecalphaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testdecalphaMenuActionPerformed
        // TODO add your handling code here:
        try {
            PengujianDecAlphaFrame dataset = new PengujianDecAlphaFrame();
            jDesktopPane1.add(dataset);
            dataset.setMaximum(true);
            dataset.show();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FormUtama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_testdecalphaMenuActionPerformed

    private void testminalphaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testminalphaMenuActionPerformed
        // TODO add your handling code here:
        try {
            PengujianMinAlphaFrame dataset = new PengujianMinAlphaFrame();
            jDesktopPane1.add(dataset);
            dataset.setMaximum(true);
            dataset.show();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FormUtama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_testminalphaMenuActionPerformed

    private void testmaxepohMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testmaxepohMenuActionPerformed
        // TODO add your handling code here:
        try {
            PengujianIterasiMaxFrame dataset = new PengujianIterasiMaxFrame();
            jDesktopPane1.add(dataset);
            dataset.setMaximum(true);
            dataset.show();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FormUtama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_testmaxepohMenuActionPerformed

    private void testdataMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testdataMenuActionPerformed
        // TODO add your handling code here:
        try {
            PengujianDatasetFrame dataset = new PengujianDatasetFrame();
            jDesktopPane1.add(dataset);
            dataset.setMaximum(true);
            dataset.show();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FormUtama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_testdataMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem bobottrainingMenu;
    private javax.swing.JMenuItem datasetMenu;
    private javax.swing.JMenuItem exitMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jaraktestingMenu;
    private javax.swing.JMenuItem jaraktrainingMenu;
    private javax.swing.JMenu lvqMenu;
    private javax.swing.JMenu testMenu;
    private javax.swing.JMenuItem testalphaMenu;
    private javax.swing.JMenuItem testdataMenu;
    private javax.swing.JMenuItem testdecalphaMenu;
    private javax.swing.JMenuItem testingMenu;
    private javax.swing.JMenuItem testmaxepohMenu;
    private javax.swing.JMenuItem testminalphaMenu;
    private javax.swing.JMenuItem trainingMenu;
    private javax.swing.JMenu viewMenu;
    // End of variables declaration//GEN-END:variables
}
