/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.github.syafiqq.entra.lvq.view;

import com.github.syafiqq.entra.lvq.observable.java.lang.OStringBuilder;
import java.util.Observer;
import javax.swing.event.InternalFrameEvent;
import javax.swing.text.DefaultCaret;

/**
 * @author Entra
 */
public class JarakTestingFrame extends ClosableInternalFrame
{
    InteractionListener listener;
    private Observer logObserver;

    /**
     * Creates new form JarakTestingFrame
     */
    public JarakTestingFrame(InteractionListener listener)
    {
        this.listener = listener;
        initComponents();
        DefaultCaret caret = (DefaultCaret) this.jTextArea1.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
        this.initializeDataObserver();
        this.addInternalFrameListener(new COpenClosableInternalFrameListener()
        {
            @Override public void internalFrameOpened(InternalFrameEvent e)
            {
                JarakTestingFrame.this.listener.getJarakTesting().addObserver(JarakTestingFrame.this.logObserver);
                JarakTestingFrame.this.callObserver();
            }

            @Override public void internalFrameClosed(InternalFrameEvent e)
            {
                JarakTestingFrame.this.listener.getJarakTesting().deleteObserver(JarakTestingFrame.this.logObserver);
            }
        });
    }

    private void callObserver()
    {
        this.jTextArea1.setText(this.listener.getJarakTesting().builder.toString());
    }

    private void initializeDataObserver()
    {
        this.logObserver = (o, arg) -> this.jTextArea1.setText(arg.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setClosable(true);
        setMaximizable(true);
        setTitle("Proses Perhitungan Jarak Data Uji (Testing)");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addGroup(layout.createSequentialGroup()
                                      .addContainerGap()
                                      .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                                      .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addGroup(layout.createSequentialGroup()
                                      .addContainerGap()
                                      .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                                      .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public interface InteractionListener
    {
        OStringBuilder getJarakTesting();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
